name: Generate Datas

on:
    schedule: # Runs at 04:00, only on Tuesday and Friday. at 4 am
        # - cron: '0 4 * * 2,5'
        - cron: "0 */12 * * *"   # run automatically every 12 hours
    workflow_dispatch:

jobs:
    build:
        name: Jobs to update datas
        runs-on: ubuntu-latest
        steps:
            # Snake Animation
            - uses: Platane/snk@master
              id: snake-gif
              with:
                  github_user_name: cabraldasilvac
                  svg_out_path: dist/github-contribution-grid-snake.svg

            - uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: output
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
