name: Generate Datas

on:
    schedule: # Runs at 04:00, only on Tuesday and Friday. at 4 am
        #- cron: '0 4 * * 2,5'
        - cron: "0 */12 * * *"   # run automatically every 12 hours
    workflow_dispatch:

    # run on every push on the main branch
    push:
        branches:
            - main

jobs:
    build:
        name: Jobs to update datas
        runs-on: ubuntu-latest

        steps:
            # Snake Animation
            #- name: Generate github-contribution-grid-snake.svg
            - uses: Platane/snk@master
              id: snake-gif
              with:
                  github_user_name: cabraldasilvac
                  svg_out_path: dist/github-contribution-grid-snake.svg

            # push the content of <build_dir> to a branch
            # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
            #- name: push github-contribution-grid-snake.svg to the output branch
            - uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: output
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
