name: Generate Datas

on:
  schedule:
    - cron: '0 4 * * 2,5'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Platane/snk

      - name: Generate github-contribution-grid-snake.svg
        run: |
          snk --user cabraldasilvac --output dist/github-contribution-grid-snake.svg

      - name: Push changes to output branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update GitHub contribution grid snake"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
