name: UpdateContributionSnake

on:
  schedule: # Run at 9 am (BRT) on the 1st of every month (12 PM UTC)
    - cron: '0 12 1 * *'

  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  generate_and_deploy_snake:
    permissions:
      contents: write
    name: Generate and Deploy Snake Animation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark
          #svg_out_path: dist/github-contribution-grid-snake.svg
          #gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
          
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
