


name: Node.js CI

on:
  schedule: # horário que será executado
    - cron: "* * * * *"

jobs:
  build:
    name: Jobs to update files
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
      - uses: actions/checkout-node@v3
      - uses: actions/setup-node@v3

        with:
          node-version: '16'
          check-latest: true
      - run: npm install
      - run: npm ci
      - run: npm test
      - run: npm run update-readme

      - run: |
          git config user.name cabraldasilvac
          git config user.email cabraldasilvac@icloud.com
          git add README.md
          git commit -m "[bot] Update README with latest info"
          git push origin main
