name: Node.js CI
on:
  schedule: # horário que será executado
    - cron: "0 */2 * * *"

jobs:
  build:
    name: Jobs to update files

    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: v16.x
        - run: npm install
        - run: npm run update-readme


